name: Generate Roadmaps

on:
  schedule:
    # Runs at 00:00 on the first day of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  generate-roadmaps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Azure Roadmap script
      run: python roadmaps/azureRoadmap.py

    - name: Run Engineering Roadmap script
      run: python roadmaps/engineeringRoadmap.py

    - name: Run FinOps Roadmap script
      run: python roadmaps/finOpsRoadmap.py

    - name: Run Operations Roadmap script
      run: python roadmaps/operationsRoadmap.py

    - name: Run Test Roadmap script
      run: python roadmaps/testRoadmap.py

    - name: Update README and create release notes
      run: |
        echo "## Latest Roadmaps Update - $(date '+%Y-%m-%d')" > roadmaps/RELEASE_NOTES.md
        echo "Roadmaps have been updated with the latest data as of $(date '+%Y-%m-%d')." >> roadmaps/RELEASE_NOTES.md
        echo "- Azure Cloud Foundations Roadmap" >> roadmaps/RELEASE_NOTES.md
        echo "- Engineering Roadmap" >> roadmaps/RELEASE_NOTES.md
        echo "- FinOps Roadmap" >> roadmaps/RELEASE_NOTES.md
        echo "- Operations Roadmap" >> roadmaps/RELEASE_NOTES.md
        echo "- Test Roadmap" >> roadmaps/RELEASE_NOTES.md
        echo "This update includes adjustments for project timelines and progress." >> roadmaps/RELEASE_NOTES.md

        echo "# Roadmaps" > roadmaps/README.md
        echo "This repository contains the following roadmaps updated monthly:" >> roadmaps/README.md
        echo "- Azure Cloud Foundations Roadmap" >> roadmaps/README.md
        echo "- Engineering Roadmap" >> roadmaps/README.md
        echo "- FinOps Roadmap" >> roadmaps/README.md
        echo "- Operations Roadmap" >> roadmaps/README.md
        echo "- Test Roadmap" >> roadmaps/README.md
        echo "## Latest Update" >> roadmaps/README.md
        cat roadmaps/RELEASE_NOTES.md >> roadmaps/README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'mclarkex'
        git config --global user.email 'mclarke.1011010@gmail.com'
        git add roadmaps/
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Update roadmaps and documentation"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{secrets.REPOSITORY_TOKEN}}

   
    - name: Create GitHub release
      if: always()
      env:
        GITHUB_TOKEN: ${{secrets.REPOSITORY_TOKEN}}
      run: |
          TAG_NAME="v$(date +'%Y%m%d')"
          RELEASE_NAME="Roadmaps Update $(date +'%Y-%m-%d')"
          BODY=$(cat roadmaps/RELEASE_NOTES.md)
          gh release create "$TAG_NAME" --title "$RELEASE_NAME" --notes "$BODY"
