name: Generate Roadmaps

on:
  schedule:
    # Runs at 00:00 on the first day of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  generate-roadmaps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./automated-reporting/requirements.txt

    - name: Run Azure Roadmap script
      run: python ./automated-reporting/roadmaps/azureRoadmap.py

    - name: Run Engineering Roadmap script
      run: python automated-reporting/roadmaps/engineeringRoadmap.py

    - name: Run FinOps Roadmap script
      run: python automated-reporting/roadmaps/finOpsRoadmap.py

    - name: Run Operations Roadmap script
      run: python automated-reporting/roadmaps/operationsRoadmap.py

    - name: Run Test Roadmap script
      run: python automated-reporting/roadmaps/testRoadmap.py

    - name: Update README and create release notes
      run: |
        echo "## Latest Roadmaps Update - $(date '+%Y-%m-%d')" > automated-reporting/roadmaps/RELEASE_NOTES.md
        echo "Roadmaps have been updated with the latest data as of $(date '+%Y-%m-%d')." >> automated-reporting/roadmaps/RELEASE_NOTES.md
        echo "- Azure Cloud Foundations Roadmap" >> automated-reporting/roadmaps/RELEASE_NOTES.md
        echo "- Engineering Roadmap" >> automated-reporting/roadmaps/RELEASE_NOTES.md
        echo "- FinOps Roadmap" >> automated-reporting/roadmaps/RELEASE_NOTES.md
        echo "- Operations Roadmap" >> automated-reporting/roadmaps/RELEASE_NOTES.md
        echo "- Test Roadmap" >> automated-reporting/roadmaps/RELEASE_NOTES.md
        echo "This update includes adjustments for project timelines and progress." >> automated-reporting/roadmaps/RELEASE_NOTES.md

        echo "# Roadmaps" > automated-reporting/roadmaps/README.md
        echo "This repository contains the following roadmaps updated monthly:" >> automated-reporting/roadmaps/README.md
        echo "- Azure Cloud Foundations Roadmap" >> automated-reporting/roadmaps/README.md
        echo "- Engineering Roadmap" >> automated-reporting/roadmaps/README.md
        echo "- FinOps Roadmap" >> automated-reporting/roadmaps/README.md
        echo "- Operations Roadmap" >> automated-reporting/roadmaps/README.md
        echo "- Test Roadmap" >> automated-reporting/roadmaps/README.md
        echo "## Latest Update" >> automated-reporting/roadmaps/README.md
        cat automated-reporting/roadmaps/RELEASE_NOTES.md >> automated-reporting/roadmaps/README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'mclarkex'
        git config --global user.email 'mclarke.1011010@gmail.com'
        git add automated-reporting/roadmaps/
        git commit -m "Update roadmaps and documentation"
        git push
      env:
        GITHUB_TOKEN: ${{secrets.REPOSITORY_TOKEN}}

    - name: Create GitHub release
      uses: actions/create-release@v1
      with:
        tag_name: "v$(date '+%Y%m%d')"
        release_name: "Roadmaps Update $(date '+%Y-%m-%d')"
        body: |
          Roadmaps have been updated with the latest data as of $(date '+%Y-%m-%d').
          - Azure Cloud Foundations Roadmap
          - Engineering Roadmap
          - FinOps Roadmap
          - Operations Roadmap
          - Test Roadmap
          This update includes adjustments for project timelines and progress.
      env:
       GITHUB_TOKEN: ${{secrets.REPOSITORY_TOKEN}}
